server {
    listen 80;
    location /api/ {
        proxy_pass http://clinicapi:8080/api/;
        proxy_set_header Host $host;
    }
    location /swagger {
        proxy_pass http://clinicapi:8080/swagger;
    }
    location /metrics {
        proxy_pass http://clinicapi:8080/metrics;
    }
}
